### ISSUE TITLE
Ryot: Unable to get Logs from console to troubleshoot AudioBookShelf sync

### ISSUE THREAD

**Issue by CyberPenguin** [bravohotel91/unraid-templates#10]
Unable to connect to Audiobookshelf using Ryot. I've raised a ticket with the Ryot creator  ([https://github.com/IgnisDa/ryot/issues/215](https://github.com/IgnisDa/ryot/issues/215)) and they have asked me to add an additional env variable `RUST_LOG=ryot=trace` to get more logs. After adding this variable and trying to access the console to see the logs I get the following error:
![image](https://github.com/bravohotel91/unraid-templates/assets/118850475/5857c8a6-84ff-4cd2-9c4d-c74b103bc894)

**To Reproduce**
1. Add env variable `RUST_LOG` with the value `ryot=trace`
![image](https://github.com/bravohotel91/unraid-templates/assets/118850475/fdc75d01-4c12-4d53-b4e5-a2f3b755d85d)
2. Open the console
3. Console flashes up with the above error then closes
4. This is stopping me being able to provide logs to troubleshoot syncing with AudioBookShelf

**Expected behavior**
The console should open and display detailed logs.

**Desktop (please complete the following information):**
 - OS: Unraid 6.12.3

**Additional context**
Apologies if this is not something that you can or should fix. I'm not great with Docker but I'm trying to learn.

**Comment by bravohotel91** [comment]
This would be something that the maintainer of the ryot container might be able to provide context on. This seems to be an issue within the container itself.

This repo is mainly for the template. If the maintainer can provide an answer to the path issue, we can add to the template.

**Comment by bravohotel91** [comment]
In addition, have you tried pulling any logs from the appdata directory itself? It might provide more context than the logs that unraid provides.
