### ISSUE TITLE
Wrong Container Path in Unraid.

### ISSUE THREAD

**Issue by kripso** [bravohotel91/unraid-templates#12]
Cosmos-server docker template  by azukaar has a wrong path set in Docker Socket configuration field.

See container path is set to: "/var/run.docker.sock" instead of "/var/run/docker.sock"
![image](https://github.com/bravohotel91/unraid-templates/assets/17431307/5129973e-5934-46dc-bf2c-6d64efd84d29)

**Comment by bravohotel91** [comment]
I have updated the template to fix this issue.
