### ISSUE TITLE
Allow selection of libraries

### ISSUE THREAD

**Issue by dhicock** [bravohotel91/unraid-templates#8]
**Is your feature request related to a problem? Please describe.**
Right now, it picks the first library of the type selected. So for me, that is 3D Movies and Anime Shows. I would like to use TV Shows and my normal Movie library

**Describe the solution you'd like**
In the settings, maybe under plex, add 2 dropdowns for Movie library, and TV library

**Describe alternatives you've considered**
I haven't found an alternative yet

**Additional context**
I can't use this like intended, with the current setup

**Comment by bravohotel91** [comment]
Hello @dhicock,

Are you looking at the application itself or the template for this issue? I'm assuming this is for the Plex-Shuffler template that was built.

Anything to be modified within the application itself will need to be submitted to the maintainer of that application. This repo is specific to the template.

**Comment by dhicock-aristocrat** [comment]
Understood, I'll open it over there. Thank you for the prompt reply
